from PyQt6 import QtCore, QtGui, QtWidgets


class UI_main(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(426, 276)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 331, 31))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 426, 21))
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(parent=self.menubar)
        self.file_menu.setObjectName("file_menu")
        self.run_menu = QtWidgets.QMenu(parent=self.menubar)
        self.run_menu.setObjectName("run_menu")
        self.info_menu = QtWidgets.QMenu(parent=self.menubar)
        self.info_menu.setObjectName("info_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.open_file = QtGui.QAction(parent=MainWindow)
        self.open_file.setObjectName("open_file")
        self.delete_file = QtGui.QAction(parent=MainWindow)
        self.delete_file.setObjectName("delete_file")
        self.action_5 = QtGui.QAction(parent=MainWindow)
        self.action_5.setObjectName("action_5")
        self.theme = QtGui.QAction(parent=MainWindow)
        self.theme.setObjectName("theme")
        self.font = QtGui.QAction(parent=MainWindow)
        self.font.setObjectName("font")
        self.size = QtGui.QAction(parent=MainWindow)
        self.size.setObjectName("size")
        self.cut = QtGui.QAction(parent=MainWindow)
        self.cut.setObjectName("cut")
        self.copy = QtGui.QAction(parent=MainWindow)
        self.copy.setObjectName("copy")
        self.paste = QtGui.QAction(parent=MainWindow)
        self.paste.setObjectName("paste")
        self.info = QtGui.QAction(parent=MainWindow)
        self.info.setObjectName("info")
        self.action_13 = QtGui.QAction(parent=MainWindow)
        self.action_13.setObjectName("action_13")
        self.toCSV = QtGui.QAction(parent=MainWindow)
        self.toCSV.setObjectName("toCSV")
        self.toXLSX = QtGui.QAction(parent=MainWindow)
        self.toXLSX.setObjectName("toXLSX")
        self.toPDF = QtGui.QAction(parent=MainWindow)
        self.toPDF.setObjectName("toPDF")
        self.run = QtGui.QAction(parent=MainWindow)
        self.run.setObjectName("run")
        self.action_3 = QtGui.QAction(parent=MainWindow)
        self.action_3.setObjectName("action_3")
        self.create_play = QtGui.QAction(parent=MainWindow)
        self.create_play.setObjectName("create_play")
        self.create_test = QtGui.QAction(parent=MainWindow)
        self.create_test.setObjectName("create_test")
        self.create_file = QtGui.QAction(parent=MainWindow)
        self.create_file.setObjectName("create_file")
        self.to_file = QtGui.QAction(parent=MainWindow)
        self.to_file.setObjectName("to_file")
        self.file_menu.addAction(self.open_file)
        self.file_menu.addAction(self.delete_file)
        self.file_menu.addAction(self.create_file)
        self.file_menu.addAction(self.to_file)
        self.run_menu.addAction(self.run)
        self.info_menu.addAction(self.info)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.run_menu.menuAction())
        self.menubar.addAction(self.info_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyQTest"))
        self.label.setText(_translate("MainWindow", "Тестирующая система PyQTest:"))
        self.label_2.setText(_translate("MainWindow", "создание интеллектуальных игр, викторин,  тестов, квизов"))
        self.file_menu.setTitle(_translate("MainWindow", "Файл"))
        self.run_menu.setTitle(_translate("MainWindow", "Выполнить"))
        self.info_menu.setTitle(_translate("MainWindow", "Справка"))
        self.open_file.setText(_translate("MainWindow", "Открыть"))
        self.delete_file.setText(_translate("MainWindow", "Удалить файл"))
        self.action_5.setText(_translate("MainWindow", "Выполнить"))
        self.theme.setText(_translate("MainWindow", "Тема оформления"))
        self.font.setText(_translate("MainWindow", "Шрифт"))
        self.size.setText(_translate("MainWindow", "Размер"))
        self.cut.setText(_translate("MainWindow", "Вырезать"))
        self.copy.setText(_translate("MainWindow", "Копировать"))
        self.paste.setText(_translate("MainWindow", "Вставить"))
        self.info.setText(_translate("MainWindow", "О программе"))
        self.action_13.setText(_translate("MainWindow", "Викторина"))
        self.toCSV.setText(_translate("MainWindow", "CSV"))
        self.toXLSX.setText(_translate("MainWindow", "XLSX"))
        self.toPDF.setText(_translate("MainWindow", "PDF"))
        self.run.setText(_translate("MainWindow", "Запустить"))
        self.action_3.setText(_translate("MainWindow", "Викторина"))
        self.create_play.setText(_translate("MainWindow", "Игра"))
        self.create_test.setText(_translate("MainWindow", "Викторина"))
        self.create_file.setText(_translate("MainWindow", "Создать"))
        self.to_file.setText(_translate("MainWindow", "Экспорт"))

class UI_CreateDialog(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(319, 134)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.filename = QtWidgets.QLineEdit(parent=Form)
        self.filename.setObjectName("filename")
        self.gridLayout.addWidget(self.filename, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.cbmode = QtWidgets.QComboBox(parent=Form)
        self.cbmode.setObjectName("cbmode")
        self.cbmode.addItem("")
        self.cbmode.addItem("")
        self.gridLayout.addWidget(self.cbmode, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.cbtype = QtWidgets.QComboBox(parent=Form)
        self.cbtype.setObjectName("cbtype")
        self.cbtype.addItem("")
        self.cbtype.addItem("")
        self.gridLayout.addWidget(self.cbtype, 0, 2, 1, 1)
        self.create_btn = QtWidgets.QPushButton(parent=Form)
        self.create_btn.setObjectName("create_btn")
        self.gridLayout.addWidget(self.create_btn, 3, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Создать"))
        self.label_2.setText(_translate("Form", "Выберите режим"))
        self.label.setText(_translate("Form", "Выберите тип"))
        self.cbmode.setItemText(0, _translate("Form", "Конструктор"))
        self.cbmode.setItemText(1, _translate("Form", "Из файла"))
        self.label_3.setText(_translate("Form", "Введите название"))
        self.cbtype.setItemText(0, _translate("Form", "Тест"))
        self.cbtype.setItemText(1, _translate("Form", "Игра"))
        self.create_btn.setText(_translate("Form", "Создать"))

class UI_ExportDialog(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(267, 165)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 241, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sqltype = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.sqltype.setObjectName("sqltype")
        self.sqltype.addItem("")
        self.sqltype.addItem("")
        self.horizontalLayout_2.addWidget(self.sqltype)
        self.fname = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.fname.setObjectName("fname")
        self.horizontalLayout_2.addWidget(self.fname)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.opn = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.opn.setObjectName("opn")
        self.horizontalLayout.addWidget(self.opn)
        self.export_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.export_btn.setObjectName("export_btn")
        self.horizontalLayout.addWidget(self.export_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Экспорт"))
        self.sqltype.setItemText(0, _translate("Form", "XLSX"))
        self.sqltype.setItemText(1, _translate("Form", "CSV"))
        self.export_btn.setText(_translate("Form", "Экспорт"))

class UI_GameShowWidget(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ask_text = QtWidgets.QLabel(parent=Form)
        self.ask_text.setText("")
        self.ask_text.setObjectName("ask_text")
        self.verticalLayout.addWidget(self.ask_text)
        self.see_btn = QtWidgets.QPushButton(parent=Form)
        self.see_btn.setObjectName("see_btn")
        self.verticalLayout.addWidget(self.see_btn)
        self.check_btn = QtWidgets.QPushButton(parent=Form)
        self.check_btn.setObjectName("check_btn")
        self.verticalLayout.addWidget(self.check_btn)
        self.ans_text = QtWidgets.QLabel(parent=Form)
        self.ans_text.setText("")
        self.ans_text.setObjectName("ans_text")
        self.verticalLayout.addWidget(self.ans_text)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.see_btn.setText(_translate("Form", "Просмотреть медиа"))
        self.check_btn.setText(_translate("Form", "Проверить"))

class UI_ShowGame(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 380, 280))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.table = QtWidgets.QTableWidget(parent=self.scrollAreaWidgetContents)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.verticalLayout_2.addWidget(self.table)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))

class UI_ShowTest(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 380, 280))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.test = QtWidgets.QVBoxLayout()
        self.test.setObjectName("test")
        self.verticalLayout.addLayout(self.test)
        self.check_btn = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.check_btn.setObjectName("check_btn")
        self.verticalLayout.addWidget(self.check_btn)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Тест PyQTest"))
        self.check_btn.setText(_translate("Form", "Подвести итог"))

class UI_TestAskWidget(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.ask_text = QtWidgets.QPlainTextEdit(parent=Form)
        self.ask_text.setObjectName("ask_text")
        self.verticalLayout.addWidget(self.ask_text)
        self.del_btn = QtWidgets.QPushButton(parent=Form)
        self.del_btn.setObjectName("del_btn")
        self.verticalLayout.addWidget(self.del_btn)
        self.media = QtWidgets.QPushButton(parent=Form)
        self.media.setObjectName("media")
        self.verticalLayout.addWidget(self.media)
        self.file_label = QtWidgets.QLabel(parent=Form)
        self.file_label.setText("")
        self.file_label.setObjectName("file_label")
        self.verticalLayout.addWidget(self.file_label)
        self.vars = QtWidgets.QPushButton(parent=Form)
        self.vars.setObjectName("vars")
        self.verticalLayout.addWidget(self.vars)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.cor = QtWidgets.QLineEdit(parent=Form)
        self.cor.setObjectName("cor")
        self.verticalLayout.addWidget(self.cor)
        self.ask = QtWidgets.QVBoxLayout()
        self.ask.setObjectName("ask")
        self.verticalLayout.addLayout(self.ask)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Вопрос"))
        self.del_btn.setText(_translate("Form", "Удалить вопрос"))
        self.media.setText(_translate("Form", "Добавить файл"))
        self.vars.setText(_translate("Form", "Добавить вариант ответа"))
        self.label_2.setText(_translate("Form", "Правильный ответ"))

class UI_GameAskWidget(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.ask_text = QtWidgets.QPlainTextEdit(parent=Form)
        self.ask_text.setObjectName("ask_text")
        self.verticalLayout.addWidget(self.ask_text)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.cor = QtWidgets.QPlainTextEdit(parent=Form)
        self.cor.setObjectName("cor")
        self.verticalLayout.addWidget(self.cor)
        self.media = QtWidgets.QPushButton(parent=Form)
        self.media.setObjectName("media")
        self.verticalLayout.addWidget(self.media)
        self.file_label = QtWidgets.QLabel(parent=Form)
        self.file_label.setText("")
        self.file_label.setObjectName("file_label")
        self.verticalLayout.addWidget(self.file_label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Вопрос"))
        self.label_2.setText(_translate("Form", "Ответ"))
        self.media.setText(_translate("Form", "Добавить файл"))

class UI_ConstructorTest(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(405, 278)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sa = QtWidgets.QScrollArea(parent=Form)
        self.sa.setWidgetResizable(True)
        self.sa.setObjectName("sa")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 385, 258))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.select_btn = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents_3)
        self.select_btn.setObjectName("select_btn")
        self.verticalLayout.addWidget(self.select_btn)
        self.save_btn = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents_3)
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout.addWidget(self.save_btn)
        self.ask = QtWidgets.QVBoxLayout()
        self.ask.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.ask.setSpacing(20)
        self.ask.setObjectName("ask")
        self.verticalLayout.addLayout(self.ask)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.sa.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.addWidget(self.sa)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Конструктор"))
        self.select_btn.setText(_translate("Form", "Добавить вопрос"))
        self.save_btn.setText(_translate("Form", "Сохранить"))

class UI_ConstructorGame(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(636, 545)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 616, 525))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.themes = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents_2)
        self.themes.setObjectName("themes")
        self.horizontalLayout_2.addWidget(self.themes)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.points = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents_2)
        self.points.setObjectName("points")
        self.horizontalLayout.addWidget(self.points)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.create = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents_2)
        self.create.setObjectName("create")
        self.verticalLayout.addWidget(self.create)
        self.save = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents_2)
        self.save.setObjectName("save")
        self.verticalLayout.addWidget(self.save)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.table = QtWidgets.QGridLayout()
        self.table.setObjectName("table")
        self.verticalLayout_2.addLayout(self.table)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Конструктор"))
        self.label.setText(_translate("Form", "Сколько тем?"))
        self.label_2.setText(_translate("Form", "Сколько вопросов в теме"))
        self.create.setText(_translate("Form", "Создать"))
        self.save.setText(_translate("Form", "Сохранить"))